#!/usr/bin/env bash

set -e

install_dir="$HOME/.local/share/bun"

rm -rf "$install_dir"
mkdir -p "$install_dir"

export BUN_INSTALL="$install_dir"
curl -fsSL https://bun.sh/install | bash

echo "bun installed successfully"
