#!/usr/bin/env bash

set -e

archive_name="google-chrome-stable_current_amd64.deb"
download_url="https://dl.google.com/linux/direct/$archive_name"

curl -LO "$download_url"

sudo dpkg -i "$archive_name"

rm "$archive_name"

echo "chrome installed successfully"
