#!/usr/bin/env bash

set -e

install_dir="$HOME/.local/bin"
package_name="nvim-linux-x86_64.appimage"
download_url="https://github.com/neovim/neovim/releases/latest/download/$package_name"

curl -LO "$download_url"

chmod u+x "$package_name"

mv "$package_name" "$HOME/.local/bin/nvim"

echo "neovim installed successfully"
