#!/usr/bin/env bash
set -e

install_dir="/opt/nvim"
archive_name="nvim-linux-x86_64.tar.gz"
download_url="https://github.com/neovim/neovim/releases/latest/download/${archive_name}"

echo "installing dependencies..."
sudo apt update && sudo apt install build-essential fzf ripgrep unzip -y

echo "removing previously installed version..."
sudo rm -rf "$install_dir"
sudo mkdir -p "$install_dir"
sudo chown "$USER:$USER" "$install_dir"

echo "downloading neovim..."
curl -LO "$download_url"

echo "extracting..."
tar -xzf "$archive_name" -C "$install_dir" --strip-components=1

echo "symlinking binary..."
sudo ln -sf "$install_dir/bin/nvim" /usr/local/bin/vi
sudo ln -sf "$install_dir/bin/nvim" /usr/local/bin/nvim

echo "cleaning up..."
rm "$archive_name"

echo "installed neovim successfully"
