#!/usr/bin/env bash
set -e

install_dir="$HOME/.local/share/nvim"
archive_name="nvim-linux-x86_64.tar.gz"
download_url="https://github.com/neovim/neovim/releases/latest/download/$archive_name"

rm -rf "$install_dir"
mkdir -p "$install_dir"

curl -LO "$download_url"

tar -xzf "$archive_name" -C "$install_dir" --strip-components=1

rm "$archive_name"

echo "neovim installed successfully"
