#!/usr/bin/env bash

sudo apt update && sudo apt install build-essential \
  curl \
  fzf \
  git \
  gh \
  ripgrep \
  tmux \
  tree-sitter-cli \
  unzip \
  wget \
  --no-install-recommends \
  --no-install-suggests \
  -y

echo "tools installed successfully"
