#!/usr/bin/env bash
set -e

install_dir="$HOME/.local/share/zen"
archive_name="zen.linux-x86_64.tar.xz"
download_url="https://github.com/zen-browser/desktop/releases/latest/download/$archive_name"

echo "removing previously installed version..."
rm -rf "$install_dir"
mkdir -p "$install_dir"

echo "downloading zen browser..."
curl -LO "$download_url"

echo "extracting..."
tar -xvJf "$archive_name" -C "$install_dir" --strip-components=1

echo "cleaning up..."
rm "$archive_name"

echo "installed zen browser successfully"
